import type {
  ControlMappable,
  Id,
  ISODateTimeString,
  TenantScoped,
  Timestamped,
  UserId,
  Versioned,
} from './common';
import type { InitiativeId } from './initiative';

/**
 * Definition Workspace (JTBD 4): Epic → Feature → Story hierarchy, process
 * flows (4a), business rules (4b), and policy/controls (4c) — the module
 * that makes the product credible in a bank or pharma.
 */

export type EpicId = Id<'Epic'>;
export type FeatureId = Id<'Feature'>;
export type StoryId = Id<'Story'>;

export interface Epic extends Timestamped, TenantScoped, Versioned {
  id: EpicId;
  initiativeId: InitiativeId;
  title: string;
  description: string;
  status: 'draft' | 'active' | 'done' | 'archived';
}

export interface Feature extends Timestamped, TenantScoped, Versioned {
  id: FeatureId;
  epicId: EpicId;
  title: string;
  description: string;
  status: 'draft' | 'active' | 'done' | 'archived';
}

export interface Story extends Timestamped, TenantScoped, ControlMappable, Versioned {
  id: StoryId;
  featureId: FeatureId;
  title: string;
  narrative: string; // "As a ... I want ... so that ..."
  acceptanceCriteria: AcceptanceCriterion[];
  definitionOfReady: DefinitionOfReadyCheck[];
  storyPoints: number | null;
  /** Jira/ADO/Rally sync — platform owns "why", external tool owns execution state (A6). */
  externalRef: ExternalWorkItemRef | null;
  /** Draft content generated by the AI Assist layer must carry provenance and stay unpromoted until a human accepts it. */
  aiDraftProvenance: AiDraftProvenance | null;
}

export interface AcceptanceCriterion {
  id: Id<'AcceptanceCriterion'>;
  given: string;
  when: string;
  then: string;
  linkedTestCaseIds: Array<Id<'TestCase'>>;
}

export interface DefinitionOfReadyCheck {
  id: Id<'DefinitionOfReadyCheck'>;
  label: string;
  satisfied: boolean;
}

export interface ExternalWorkItemRef {
  system: 'jira' | 'azure_devops' | 'rally';
  externalId: string;
  externalUrl: string;
  lastSyncedAt: ISODateTimeString;
}

export interface AiDraftProvenance {
  modelGatewayRequestId: string;
  generatedAt: ISODateTimeString;
  acceptedBy: UserId | null;
  acceptedAt: ISODateTimeString | null;
  editedBeforeAccept: boolean;
}

/** Traceability matrix row: requirement ↔ rule ↔ control ↔ test coverage. */
export interface TraceabilityLink {
  id: Id<'TraceabilityLink'>;
  storyId: StoryId;
  businessRuleIds: Array<Id<'BusinessRule'>>;
  controlIds: Array<Id<'Control'>>;
  testCaseIds: Array<Id<'TestCase'>>;
}

// --- 4a. Process modeling -------------------------------------------------

export type ProcessFlowState = 'current' | 'target';

/** Diagram-as-data: nodes/edges in JSON, rendered client-side with React Flow. */
export interface ProcessFlow extends Timestamped, TenantScoped, Versioned {
  id: Id<'ProcessFlow'>;
  initiativeId: InitiativeId;
  state: ProcessFlowState;
  /** Pairs a current-state flow with its target-state counterpart so the delta can be computed. */
  pairedFlowId: Id<'ProcessFlow'> | null;
  nodes: ProcessFlowNode[];
  edges: ProcessFlowEdge[];
}

export interface ProcessFlowNode {
  id: string;
  label: string;
  kind: 'start' | 'end' | 'task' | 'decision' | 'system';
  position: { x: number; y: number };
  linkedStoryIds: StoryId[];
  linkedRuleIds: Array<Id<'BusinessRule'>>;
}

export interface ProcessFlowEdge {
  id: string;
  sourceNodeId: string;
  targetNodeId: string;
  label: string | null;
}

/** Explicit change scope: computed delta between a current/target flow pair, persisted for reporting. */
export interface ProcessFlowDelta {
  currentFlowId: Id<'ProcessFlow'>;
  targetFlowId: Id<'ProcessFlow'>;
  addedNodeIds: string[];
  removedNodeIds: string[];
  changedNodeIds: string[];
}

// --- 4b. Business rules ----------------------------------------------------

export interface BusinessRule extends Timestamped, TenantScoped, Versioned {
  id: Id<'BusinessRule'>;
  initiativeId: InitiativeId;
  ruleCode: string; // e.g. "BR-014"
  condition: string;
  action: string;
  ownerId: UserId;
  sourceSystem: string | null;
  effectiveFrom: ISODateTimeString | null;
  effectiveTo: ISODateTimeString | null;
  linkedStoryIds: StoryId[];
  testCoverageStatus: 'none' | 'partial' | 'full';
}

// --- 4c. Policy & controls --------------------------------------------------

export type ControlId = Id<'Control'>;

export interface PolicyReference extends Timestamped, TenantScoped {
  id: Id<'PolicyReference'>;
  name: string;
  externalSystem: 'archer' | 'metricstream' | 'openpages' | 'manual';
  externalRef: string | null;
}

export interface Control extends Timestamped, TenantScoped {
  id: ControlId;
  policyId: Id<'PolicyReference'>;
  code: string; // e.g. "CTRL-SOX-014"
  description: string;
}

export type AttestationState = 'not_started' | 'in_progress' | 'attested' | 'exception_requested';

/** Per-initiative control register row: which control applies, evidence, attestation state. */
export interface InitiativeControlMapping extends Timestamped, TenantScoped {
  id: Id<'InitiativeControlMapping'>;
  initiativeId: InitiativeId;
  controlId: ControlId;
  evidenceAttachmentIds: Array<Id<'Attachment'>>;
  attestationState: AttestationState;
  attestedBy: UserId | null;
  attestedAt: ISODateTimeString | null;
}
